### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by iauei** [Dr-TSNG/ApplistDetector#11]
delete

**Comment by cracky5322** [comment]
@iauei Is there only option system framework in LSPosed?

**Comment by iauei** [comment]
> @iauei Is there only option system framework in LSPosed?

I do not quite understand what you are writing about.
I have LSPosed with 2 modules Hide My Applist and Android Faker

If turn on Android Faker, AppListDetecrot will show an error Xposed hooks found

**Comment by cracky5322** [comment]
@iauei What HMA chooses in LSPosed Manager

**Comment by iauei** [comment]
> @iauei What HMA chooses in LSPosed Manager

I can't understand. What is it HMA 

https://ibb.co/8sz7phx
https://ibb.co/rvTK5pt
https://ibb.co/KxNdFr8

my screenshots

**Comment by iauei** [comment]
> @iauei What HMA chooses in LSPosed Manager

https://ibb.co/m8Bk5xP

Only system framework
