### ISSUE TITLE
全部通过，12306人脸识别还是报错1001

### ISSUE THREAD

**Issue by AoEiuV020** [Dr-TSNG/ApplistDetector#12]
不知道12306是怎么检测的，
手机小米mix4，解锁前是正常的，
现在解锁刷了magisk，装了一堆隐藏相关模块，safetynet也过了，这里的检测也过了，12306还是不行，应该不是脸的问题，
![Screenshot_2022-01-04-03-33-53-302_com MobileTicket](https://user-images.githubusercontent.com/11682198/147972408-b9190b36-1e8e-4734-8e00-e6d2485bc1f7.jpg)
![Screenshot_2022-01-04-03-32-51-213_com tsng applistdetector](https://user-images.githubusercontent.com/11682198/147972412-693036c3-beb9-4b0a-bde9-99b69bee4996.jpg)

**Comment by cracky5322** [comment]
那跟這裡有什麼關系？這個應用只是在輔助你檢查是否有被檢測到，如果真的要問也是去 HMA 問。
就算去 HMA 問了，檢測器顯示你全數通過，如果全數通過那就不是 HMA 的問題了。
在我們看來這篇純屬垃圾訊息。

**Comment by AoEiuV020** [comment]
@cracky5322 我想说是否有办法知道12306的检测方法，这里加上一样的检测，以便其他负责隐藏的模块针对处理，

**Comment by ckdkl** [comment]
现在解决了吗，我也遇到这个问题了

**Comment by AoEiuV020** [comment]
> 现在解决了吗，我也遇到这个问题了

不知道到底啥问题，总之我刚试了一下正常，
我现在用的是小米12sp， miui 14, magisk 25.2, zygisk, shamiko, hidemyapplist,
