### ISSUE TITLE
Libc Detected In V2

### ISSUE THREAD

**Issue by George-Seven** [Dr-TSNG/ApplistDetector#13]
Android 10, MIUI
Redmi Note 9 Pro Max

![1](https://user-images.githubusercontent.com/92206927/153055003-13a84d3f-8329-4c35-840b-25bee51b9bf1.jpeg)

Log -

`2022-02-09 00:09:58 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getInstalledPackages`
`2022-02-09 00:09:58 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getInstalledPackages`
`2022-02-09 00:09:58 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getInstalledApplications`
`2022-02-09 00:09:58 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getPackageUid param: moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: queryIntentActivities`
`2022-02-09 00:09:58 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: queryIntentActivities`
`2022-02-09 00:09:58 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /data/data/moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /data/data/moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage`
`2022-02-09 00:09:58 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: queryIntentActivities`

But previous version,

![2](https://user-images.githubusercontent.com/92206927/153055198-af3883da-8cb8-4499-8a65-d0b1e3869fb3.jpeg)

Log -
`2022-02-09 00:11:47 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: getInstalledPackages`
`2022-02-09 00:11:47 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: getInstalledPackages`
`2022-02-09 00:11:47 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: getInstalledApplications`
`2022-02-09 00:11:47 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: queryIntentActivities`
`2022-02-09 00:11:47 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: getPackageUid param: moe.shizuku.redirectstorage`
`2022-02-09 00:11:47 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: queryIntentActivities`
`2022-02-09 00:11:47 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: getPackagesHoldingPermissions`
`2022-02-09 00:11:48 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: queryIntentActivities`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /data/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /data/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /data/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /data/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /data/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Native] [INFO] @Hide syscall intercept | caller: com.tsng.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage`
`2022-02-09 00:11:48 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: queryIntentActivities`
`2022-02-09 00:11:48 [HMA Xposed] [INFO] @Hide PMS caller: com.tsng.applistdetector method: queryIntentActivities`

**Comment by xcsnowcity** [comment]
Same issue here.


 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getInstalledPackages
 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getInstalledPackages
 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getInstalledApplications
 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getPackageUid param: moe.shizuku.redirectstorage
 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: getInstallSourceInfo param: moe.shizuku.redirectstorage
 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: queryIntentActivities
 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: queryIntentActivities
 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /data/data/moe.shizuku.redirectstorage
 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /data/data/moe.shizuku.redirectstorage
 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage
 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage
 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage
 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/media/moe.shizuku.redirectstorage
 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage
 [HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/obb/moe.shizuku.redirectstorage
 [HMA Xposed] [INFO] @Hide PMS caller: icu.nullptr.applistdetector method: queryIntentActivities
 
Obviously HMA is working properly, and previous version of this app which is 1.3.2 can't detect redirectstorage app but had the same log . So all in all, it's a strange situation.

**Comment by xcxnig** [comment]
[HMA Native] [INFO] @Hide syscall intercept | caller: icu.nullptr.applistdetector param: /storage/emulated/0/Android/data/moe.shizuku.redirectstorage
 
 这条日志是导致 moe.shizuku.redirectstorage 被检测出的原因

测试方法： 删除 /storage/emulated/0/Android/data/moe.shizuku.redirectstorage 文件夹
优点：简单粗暴、无副作用
缺点： 不优雅、App后会重新生成

**Comment by George-Seven** [comment]
Tried test method and ot didn't work, made sure to run detector before folder regenerates, but still detected regardless.
