### ISSUE TITLE
Detects magisk using magisk hide.

### ISSUE THREAD

**Issue by fusk-l** [Dr-TSNG/ApplistDetector#21]
Maybe i'm using it wrong, or magisk hide isn't so great at hiding it self. But applist detector detects magisk on my phone, and i don't know why it's detecting it when magisk hide is active. It's detecting "ij.zkqebr"

**Comment by Dr-TSNG** [comment]
magisk hide does not hide package name

**Comment by fusk-l** [comment]
When you say "package name" what exactly do you mean. I just want to make sure i fully understand it. Right now magisk is hidden and renamed to "Manege", yet being detected. Does it have something to do with "ij.zkqebr" ?

**Comment by Dr-TSNG** [comment]
read the code urself. it's open source

**Comment by fusk-l** [comment]
Well, if that was a thing, then yeah i'd started with that.
