### ISSUE TITLE
Maybe missing some detection methods

### ISSUE THREAD

**Issue by snowman** [Dr-TSNG/ApplistDetector#9]
Like:
1. `getInstalledPackages`
2. `getInstalledApplications`
3. `getPackageUid`
4. `java File` 
5. etc

#### Before
![024](https://user-images.githubusercontent.com/16096559/140251914-90b6982b-f440-4f1e-8d7f-114231efe95b.png)

#### After
![2](https://user-images.githubusercontent.com/16096559/140266411-ff3fae3a-2dd2-41b7-a38a-610c3856cac4.png)

**Comment by Dr-TSNG** [comment]
That's the same as conventional methods & libc
